name: Test CI

on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test
